import Foundation

public enum AppLanguage: String, CaseIterable, Identifiable, Sendable {
    case simplifiedChinese = "zh-Hans"
    case traditionalChinese = "zh-Hant"
    case english = "en"

    public var id: String { rawValue }

    public var displayName: String {
        switch self {
        case .simplifiedChinese: return "简体中文"
        case .traditionalChinese: return "繁體中文"
        case .english: return "English"
        }
    }

    public static func normalize(_ value: String) -> AppLanguage {
        switch value {
        case "zh-Hant", "zh_TW", "zh-HK", "zh-TW":
            return .traditionalChinese
        case "en", "en-US", "en-GB":
            return .english
        default:
            return .simplifiedChinese
        }
    }
}

public enum L10n {
    public static func text(_ key: String, language value: String) -> String {
        switch AppLanguage.normalize(value) {
        case .simplifiedChinese:
            return key
        case .traditionalChinese:
            return traditionalOverrides[key] ?? key.convertedToTraditionalChinese()
        case .english:
            return english[key] ?? key
        }
    }

    private static let traditionalOverrides: [String: String] = [
        "3FUI": "3FUI",
        "FFmpegFreeSwiftUI": "FFmpegFreeSwiftUI",
        "ffmpeg": "ffmpeg",
        "ffprobe": "ffprobe",
        "ffplay": "ffplay",
        "macOS 首版不绑定 affinity": "macOS 首版不綁定 affinity",
        "PATH": "PATH"
    ]

    private static let english: [String: String] = [
        "添加文件到编码队列...": "Add Files to Encoding Queue...",
        "导入预设...": "Import Preset...",
        "导出当前预设...": "Export Current Preset...",
        "设置...": "Settings...",
        "插件扩展": "Plugin Extensions",
        "支持者": "Supporters",
        "导航": "Navigation",
        "3FUI": "3FUI",
        "编码队列": "Encoding Queue",
        "准备文件": "Prepare Files",
        "参数面板": "Parameter Panel",
        "媒体信息": "Media Info",
        "播放器": "Player",
        "画质评测": "Quality Assessment",
        "混流": "Muxing",
        "合并": "Merging",
        "性能监控": "Performance Monitor",
        "设置": "Settings",
        "添加文件...": "Add Files...",
        "开始未处理任务": "Start Pending Tasks",
        "开始选中任务": "Start Selected Task",
        "暂停选中任务": "Pause Selected Task",
        "恢复选中任务": "Resume Selected Task",
        "停止选中任务": "Stop Selected Task",
        "移除选中任务": "Remove Selected Task",
        "重置选中任务": "Reset Selected Task",
        "复制任务命令行": "Copy Task Command Line",
        "在 Finder 中显示输出": "Show Output in Finder",
        "参数/预设": "Parameters / Presets",
        "重置当前参数": "Reset Current Parameters",
        "参数面板覆盖到选中任务": "Apply Panel to Selected Task",
        "选中任务参数覆盖到参数面板": "Load Selected Task into Panel",
        "工具": "Tools",
        "文件": "File",
        "帮助": "Help",
        "性能调度": "Performance Scheduling",
        "自动同时运行任务数量": "Concurrent Tasks",
        "编码队列刷新速度": "Queue Refresh Rate",
        "指定处理器核心（保留设置，macOS 首版不绑定 affinity）": "Preferred CPU cores (saved only; affinity is not bound in the first macOS version)",
        "功能设定": "Behavior",
        "自动开始任务": "Start tasks automatically",
        "启用提示音": "Enable sounds",
        "自动重置参数面板到第一个页面": "Reset parameter panel to first page on launch",
        "任务名称混淆": "Obfuscate task names",
        "任务失败删除输出文件策略": "Failed-output deletion policy",
        "工作目录": "Working directory",
        "FFmpeg 路径": "FFmpeg Paths",
        "自动检测": "Auto Detect",
        "写入检测结果": "Apply Detected Paths",
        "清空自定义路径": "Clear Custom Paths",
        "替代 ffmpeg 文件名": "Custom ffmpeg path",
        "替代 ffprobe 文件名": "Custom ffprobe path",
        "替代 ffplay 文件名": "Custom ffplay path",
        "覆盖参数传递，使用 <args>": "Override argument passthrough, use <args>",
        "检测结果": "Detection Results",
        "未检测": "Not detected",
        "未找到": "Not found",
        "来源": "Source",
        "用户设置": "User setting",
        "App 同级目录": "App sibling directory",
        "环境变量 PATH": "PATH environment",
        "常见安装目录": "Common install directory",
        "远程调用": "Remote Control",
        "启用 UDP 监听": "Enable UDP listener",
        "端口": "Port",
        "应用远程调用设置": "Apply Remote Settings",
        "界面显示": "Display",
        "全局字体": "Global font",
        "语言": "Language",
        "简体中文": "Simplified Chinese",
        "繁體中文": "Traditional Chinese",
        "繁体中文": "Traditional Chinese",
        "中文": "Chinese",
        "English": "English",
        "将 ffmpeg、ffplay、ffprobe 加入环境变量、放在 App 同级目录，或在设置中指定路径即可调用。": "Put ffmpeg, ffplay, and ffprobe in PATH, next to the app, or specify their paths in Settings.",
        "主要逻辑": "Main Workflow",
        "先在参数面板设定选项，再把文件拖进编码队列。加入队列时会保存当前参数快照，任务开始时生成命令行。": "Set options in the Parameter Panel, then drag files into the Encoding Queue. Each queued task keeps a parameter snapshot and builds its command when it starts.",
        "macOS 版使用原生 Process、Unix signal、Finder 定位、caffeinate 防睡眠和 JSON 预设。": "The macOS version uses native Process APIs, Unix signals, Finder reveal, caffeinate sleep prevention, and JSON presets.",
        "链接和文档": "Links and Docs",
        "3FUI GitHub 仓库": "3FUI GitHub Repository",
        "FFmpeg 官方文档": "FFmpeg Documentation",
        "下载 FFmpeg": "Download FFmpeg",
        "输出路径": "Output Path",
        "浏览...": "Browse...",
        "已刷新检测结果": "Detection results refreshed",
        "已写入可执行路径": "Executable paths applied",
        "没有找到可写入的可执行路径": "No executable paths were found to apply",
        "已清空自定义路径": "Custom paths cleared",
        "自动检测会按用户设置、App 同级目录、PATH 和常见安装目录查找；留空自定义路径时也会自动使用检测到的位置。": "Auto detection checks custom settings, app sibling directories, PATH, and common install locations. Blank custom paths still use detected locations automatically.",
        "可执行": "Executable",
        "不可执行": "Not executable",
        "路径": "Path",
        "状态": "Status",
        "命令行工具": "Command-line Tool",
        "参数总览": "Overview",
        "实际命令行": "Command Line",
        "输出文件设置": "Output File Settings",
        "解码设置": "Decoding",
        "视频参数编码器": "Video Encoder",
        "视频参数画面帧": "Video Frame",
        "视频参数质量": "Video Quality",
        "视频参数色彩管理": "Color Management",
        "视频参数常见滤镜": "Common Filters",
        "视频帧服务器": "Frame Server",
        "音频参数": "Audio",
        "图片参数": "Image",
        "自定义参数": "Custom Arguments",
        "剪辑区间": "Clip Range",
        "流控制": "Stream Control",
        "方案管理": "Preset Management",
        "输出容器": "Output Container",
        "输出位置": "Output Location",
        "不附加输出文件参数": "Omit Output File Argument",
        "使用自动命名": "Use Auto Naming",
        "自动命名选项": "Auto Naming Option",
        "开头文本": "Prefix Text",
        "替代文本": "Replacement Text",
        "结尾文本": "Suffix Text",
        "文件时间": "File Timestamps",
        "创建": "Created",
        "修改": "Modified",
        "访问": "Accessed",
        "解码器": "Decoder",
        "CPU 解码线程数": "CPU Decoder Threads",
        "解码数据格式": "Decoded Format",
        "指定硬件参数名": "Hardware Argument Name",
        "指定硬件参数": "Hardware Argument",
        "类别": "Category",
        "具体编码": "Encoder",
        "编码预设": "Preset",
        "配置文件": "Profile",
        "场景优化": "Tune",
        "控制方式": "Control Mode",
        "质量参数名": "Quality Argument",
        "质量值": "Quality Value",
        "比特率基础": "Base Bitrate",
        "最低值": "Minimum",
        "最高值": "Maximum",
        "缓冲区": "Buffer",
        "进阶参数集": "Advanced Arguments",
        "分辨率": "Resolution",
        "自动宽度": "Auto Width",
        "自动高度": "Auto Height",
        "裁剪滤镜参数": "Crop Filter",
        "帧速率": "Frame Rate",
        "逐行与隔行": "Progressive / Interlaced",
        "角度翻转": "Rotate",
        "镜像翻转": "Mirror",
        "像素格式": "Pixel Format",
        "滤镜选择": "Filter",
        "矩阵系数": "Matrix",
        "色域": "Primaries",
        "传输特性": "Transfer",
        "范围": "Range",
        "色调映射算法": "Tonemap",
        "处理方式": "Process Mode",
        "亮度": "Brightness",
        "对比度": "Contrast",
        "饱和度": "Saturation",
        "伽马": "Gamma",
        "降噪方式": "Denoise Mode",
        "烧录字幕": "Burn Subtitles",
        "外部字幕": "External Subtitle",
        "外部字幕文件名": "External Subtitle File",
        "外部字幕文件夹": "External Subtitle Folder",
        "内嵌字幕流": "Embedded Subtitle Stream",
        "指定内嵌的流": "Embedded Stream",
        "字体文件夹": "Fonts Folder",
        "自定义样式": "Custom Style",
        "自定义滤镜参数": "Custom Filter Arguments",
        "使用 AviSynth": "Use AviSynth",
        "avs 脚本文件": "AVS Script",
        "使用 VapourSynth": "Use VapourSynth",
        "vpy 脚本文件": "VPY Script",
        "比特率": "Bitrate",
        "声道数": "Channels",
        "采样率": "Sample Rate",
        "目标响度": "Target Loudness",
        "动态范围": "Dynamic Range",
        "峰值电平": "Peak Level",
        "编码名称": "Encoder Name",
        "视频滤镜": "Video Filter",
        "音频滤镜": "Audio Filter",
        "视频参数": "Video Arguments",
        "音频自定义参数": "Audio Arguments",
        "开头参数": "Leading Arguments",
        "之前参数": "Before Output Arguments",
        "之后参数": "After Output Arguments",
        "最后参数": "Trailing Arguments",
        "完全自己写": "Full Custom Command",
        "方法": "Method",
        "入点": "In Point",
        "出点": "Out Point",
        "向前解码多久秒": "Pre-decode Seconds",
        "保留其他视频流": "Keep Other Video Streams",
        "视频指定流": "Video Stream Targets",
        "保留其他音频流": "Keep Other Audio Streams",
        "音频指定流": "Audio Stream Targets",
        "字幕指定流": "Subtitle Stream Targets",
        "字幕操作": "Subtitle Operation",
        "保留其他字幕流": "Keep Other Subtitle Streams",
        "自动混流": "Auto Mux",
        "转 MOVTEXT": "To MOVTEXT",
        "元数据选项": "Metadata Option",
        "章节选项": "Chapter Option",
        "附件选项": "Attachment Option",
        "新建方案": "New Preset",
        "导入 .3fui / JSON": "Import .3fui / JSON",
        "导出 .3fui": "Export .3fui",
        "自动加载预设": "Auto Load Preset",
        "指定预设路径": "Preset Path",
        "任务开始时生成命令行": "Command line is generated when the task starts",
        "性能监控会在切到其他选项卡时自动暂停；当前显示 CPU、内存、磁盘和编码队列负载": "Performance monitoring pauses when switching tabs; it currently shows CPU, memory, disk, and encoding queue load.",
        "CPU 逻辑核心": "CPU Logical Cores",
        "系统概览": "System Overview",
        "内存": "Memory",
        "磁盘": "Disk",
        "运行中 / 未处理": "Running / Pending",
        "旧": "Older",
        "现在": "Now",
        "等待下一次采样": "Waiting for next sample",
        "添加文件": "Add Files",
        "开始": "Start",
        "暂停": "Pause",
        "恢复": "Resume",
        "停止": "Stop",
        "移除": "Remove",
        "重置": "Reset",
        "定位": "Reveal",
        "任务管理菜单": "Task Actions",
        "向 ffmpeg 发送 stdin 消息": "Send stdin message to ffmpeg",
        "发送": "Send",
        "捕获错误": "Capture Errors",
        "实时输出": "Live Output",
        "命令行": "Command Line",
        "输出目录": "Output Directory",
        "自定义输出目录（留空则跟随预设或输入目录）": "Custom output directory (blank follows preset or input directory)",
        "加入编码队列": "Add to Encoding Queue",
        "媒体文件路径": "Media file path",
        "选择文件": "Choose File",
        "调用 ffprobe": "Run ffprobe",
        "复制输出": "Copy Output",
        "播放": "Play",
        "仅提供最基础的混流，高级功能请移步 MKVToolNix GUI；分离请用 MKVExtract GUI": "Only basic muxing is provided. Use MKVToolNix GUI for advanced work and MKVExtract GUI for extraction.",
        "仅提供最基础的合并，仅复制流，要求多个参数一致；高级需求请直接用剪辑软件": "Only basic concat is provided. Streams are copied and inputs must share matching parameters; use an editor for advanced needs.",
        "上移": "Move Up",
        "下移": "Move Down",
        "选择位置": "Choose Location",
        "启动混流": "Start Muxing",
        "启动合并": "Start Merging",
        "输出到目标位置": "Output destination",
        "视频质量评测并不能代表绝对表现，其会受到各种因素的影响，请以人眼视觉为准": "Video quality metrics are not absolute and can be affected by many factors; trust visual inspection first.",
        "重置页面": "Reset Page",
        "全新开始评测": "Start New Assessment",
        "从选择处开始": "Start from Selection",
        "原视频": "Reference Video",
        "选择原视频文件": "Choose reference video",
        "编码后的文件": "Encoded Files",
        "添加编码后的文件": "Add Encoded Files",
        "指标": "Metrics",
        "通用配置 / VMAF 配置": "General / VMAF Configuration",
        "浏览": "Browse",
        "最近结果": "Recent Results",
        "最低": "Minimum",
        "复制": "Copy",
        "日志": "Log",
        "测评队列": "Assessment Queue",
        "结果历史": "Result History",
        "实时日志": "Live Log",
        "清空历史": "Clear History"
    ]
}

private extension String {
    func convertedToTraditionalChinese() -> String {
        let mutable = NSMutableString(string: self)
        CFStringTransform(mutable, nil, "Hans-Hant" as CFString, false)
        return mutable as String
    }
}
